# config.yaml
# Network configuration
network:
  websocket_url: "wss://s.altnet.rippletest.net:51233"  # Default to testnet
  max_reconnect_attempts: 5
  reconnect_delay_seconds: 5

# Wallet configuration
wallets:
  target_wallet: ""
  follower_seed: ""

# Trading configuration
trading:
  initial_purchase_amount: "1"
  min_trust_line_amount: "1000"
  max_trust_line_amount: "10000"
  send_max_xrp: "85"      # Maximum XRP to spend per purchase
  slippage_percent: "5"   # Allowed slippage in percent

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  filename: "xrpl_trader.log"

# Monitoring configuration
monitoring:
  min_trade_volume: 1000    # Minimum trade volume to log
  min_trust_lines: 5        # Number of trust lines before token is marked as "interesting"
  data_file: "token_data.json"  # File for storing token data
  save_interval_minutes: 5      # Save state every 5 minutes

# Analytics configuration
analytics:
  price_check_interval_minutes: 5  # How often to check prices
  min_liquidity: 1000             # Minimum liquidity for price tracking
  max_slippage: 10                # Maximum allowed slippage for price checks

