# Network configuration
network:
  websocket_url: "wss://s.altnet.rippletest.net:51233"  # Default to testnet
  max_reconnect_attempts: 5
  reconnect_delay_seconds: 5

# Wallet configuration
wallets:
  target_wallet: ""
  follower_seed: ""

# Trading configuration
trading:
  initial_purchase_amount: "1"
  min_trust_line_amount: "1000"
  max_trust_line_amount: "10000"

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  filename: "xrpl_trader.log"

monitoring:
  min_trade_volume: 1000
  min_trust_lines: 5
  data_file: "token_data.json"  # Valfritt, default är 'token_data.json'
  save_interval_minutes: 5  # Spara var 5:e minut

# Trading configuration
trading:
  initial_purchase_amount: "1"
  min_trust_line_amount: "1000"
  max_trust_line_amount: "10000"
  send_max_xrp: "85"      # Maximum XRP to spend per purchase
  slippage_percent: "5"    # Allowed slippage in percent